### ISSUE TITLE
taucmdr Makefile doesn't find the compilers in my path

### ISSUE THREAD

**Issue by rouson** [ParaToolsInc/taucmdr#288]
The excerpted transcript below demonstrates that the Makefile in `taucmdr` fails to find the compilers that are in my `PATH` and are installed in `/opt`:
```bash
$ which gcc g++ gfortran
/opt/gnu/8.1.0/bin/gcc
/opt/gnu/8.1.0/bin/g++
/opt/gnu/8.1.0/bin/gfortran
$ git clone https://github.com/paratoolsinc/taucmdr
$ cd taucmdr/
$ sudo make install INSTALLDIR=/opt/taucmdr TAU=minimal
```
---  snip ---
```bash
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] GNU compilers (required to build TAU) could not be found.
[TAU] 
[TAU] Hint: Try `configure --help`
[TAU] 
[TAU] Please check the selected experiment or send '/home/rouson/.local/taucmdr/debug_log' to <support@paratools.com> for 
[TAU]     assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Makefile:160: recipe for target 'install' failed
make: *** [install] Error 156
rouson@sourcery-VirtualBox:~/Desktop/taucmdr$ 
```

**Comment by rouson** [comment]
Setting the `CC`, `CXX`, and `FC`environment variables as follows yields the same result:
```bash
CC=gcc CXX=g++ FC=gfortran sudo make install INSTALLDIR=/opt/taucmdr
```
even though the GNU compilers are in my PATH:
```bash
$ echo $PATH
/home/rouson/Scripts:/opt/opencoarrays/2.1.0-30-c0e3ff/gnu/8.1.0/bin:/opt/mpich/3.2.1/gnu/8.1.0/bin:/opt/gnu/8.1.0/bin:/opt/cmake/3.11.4/gnu/8.1.0/bin/:/home/rouson/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
I'm attaching the resulting `debug_log` file.
[debug_log.tar.gz](https://github.com/ParaToolsInc/taucmdr/files/2186504/debug_log.tar.gz)

**Comment by rouson** [comment]
Problem solved via 
```bash
sudo env LD_LIBRARY_PATH=$LD_LIBRARY_PATH PATH=$PATH make install INSTALLDIR=/opt/taucmdr
```

**Comment by zbeekman** [comment]
Just FYI @rouson it is recommended that each user install their own copy of TAU Commander, so you may want to install it into your home directory instead of /opt/. Also, we have some bug fixes and other features (like coarray support) that need to be merged into `master` from `unstable`. You may have a better experience using `unstable`. You can just do `git fetch origin && git checkout unstable && make clean && ... make INSTALLDIR=... install` and safely install ontop of the existing installation or into `${HOME}/taucmdr`
